[[pages]]
path = "pages/homepage.py"
name = "MLOps on GCP"
url_path = "homepage"
icon = "ğŸ "

[[pages]]
path = "pages/create.py"
name = "Create a new deployment"
url_path = "create"
icon = "ğŸš€"

[[pages]]
path = "pages/pipeline.py"
name = "Configure MLOps pipelines"
url_path = "pipeline"
icon = "ğŸ› ï¸"

[[pages]]
path = "pages/detail.py"
name = "View deployment details"
url_path = "detail"
icon = "ğŸ“Š"



#[[pages]]
#path = "pages/create.py"
#name = "Create a new deployment"
#url_path = "create"
#icon = "â•"
#
#
#
#[[pages]]
#path = "pages/list.py"
#name = "List deployments"
#url_path = "list"
#icon = "ğŸ“‹"
#
#
#[[pages]]
#path = "pages/detail.py"
#name = "Detail deployment"
#url_path = "detail"
#icon = "ğŸ“Š"
